package chegg;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.JTextArea;

public class HangmanG extends javax.swing.JPanel{
private int count;
private static String[] words = {"WELCOME", "AERONAUTICS", "TELEPHONE", "VEHICLE",
"CELLULAR", "SOFTWARE", "PRACTICE", "ANNOYING", "AWESOME", "GUESSED"};
private int currentWord;

/**
* Creates new form hangmanG
*/
public HangmanG() {
initComponents();
count = 0;
currentWord = 0;
screen2.setVisible(false);
guesses.setVisible(false);
}  

/**
* This method is called from within the constructor to initialize the form.
* WARNING: Do NOT modify this code. The content of this method is always
* regenerated by the Form Editor.
*/
//SuppressWarnings("unchecked")
//
private void initComponents() {

heading = new javax.swing.JTextField();
A = new javax.swing.JButton();
F = new javax.swing.JButton();
B = new javax.swing.JButton();
javax.swing.JButton D = new javax.swing.JButton();
C = new javax.swing.JButton();
G = new javax.swing.JButton();
E = new javax.swing.JButton();
J = new javax.swing.JButton();
I = new javax.swing.JButton();
M = new javax.swing.JButton();
K = new javax.swing.JButton();
L = new javax.swing.JButton();
N = new javax.swing.JButton();
U = new javax.swing.JButton();
P = new javax.swing.JButton();
V = new javax.swing.JButton();
O = new javax.swing.JButton();
Q = new javax.swing.JButton();
R = new javax.swing.JButton();
S = new javax.swing.JButton();
T = new javax.swing.JButton();
W = new javax.swing.JButton();
X = new javax.swing.JButton();
Y = new javax.swing.JButton();
Z = new javax.swing.JButton();
screen1 = new javax.swing.JLabel();
guesses = new javax.swing.JLabel();
screen2 = new javax.swing.JLabel();
startStopBtn = new javax.swing.JButton();
invalidTFeild = new javax.swing.JTextField();

heading.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
heading.setText("Welcome to Hangman");
heading.setToolTipText("");
heading.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEvent evt) {
headingActionPerformed(evt);
}
});

A.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
A.setText("A");
A.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEvent evt) {
AActionPerformed(evt);
}
});

F.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
F.setText("F");
F.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEvent evt) {
FActionPerformed(evt);
}
});

B.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
B.setText("B");
B.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEvent evt) {
BActionPerformed(evt);
}
});

D.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
D.setText("D");
D.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEvent evt) {
DActionPerformed(evt);
}
});

C.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
C.setText("C");
C.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEvent evt) {
CActionPerformed(evt);
}
});

G.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
G.setText("G");
G.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEvent evt) {
GActionPerformed(evt);
}
});

E.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
E.setText("E");
E.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEvent evt) {
EActionPerformed(evt);
}
});

J.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
J.setText("J");
J.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEvent evt) {
JActionPerformed(evt);
}
});

I.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
I.setText("I");
I.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEvent evt) {
IActionPerformed(evt);
}
});

M.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
M.setText("M");
M.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEvent evt) {
MActionPerformed(evt);
}
});

K.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
K.setText("K");
K.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEvent evt) {
KActionPerformed(evt);
}
});

L.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
L.setText("L");
L.setToolTipText("");
L.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEvent evt) {
LActionPerformed(evt);
}
});

N.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
N.setText("N");
N.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEvent evt) {
NActionPerformed(evt);
}
});

U.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
U.setText("U");
U.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEvent evt) {
UActionPerformed(evt);
}
});

P.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
P.setText("P");
P.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEvent evt) {
PActionPerformed(evt);
}
});

V.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
V.setText("V");
V.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEvent evt) {
VActionPerformed(evt);
}
});

O.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
O.setText("O");
O.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEvent evt) {
OActionPerformed(evt);
}
});

Q.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
Q.setText("Q");
Q.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEvent evt) {
QActionPerformed(evt);
}
});

R.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
R.setText("R");
R.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEvent evt) {
RActionPerformed(evt);
}
});

S.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
S.setText("S");
S.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEvent evt) {
SActionPerformed(evt);
}
});

T.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
T.setText("T");
T.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEvent evt) {
TActionPerformed(evt);
}
});

W.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
W.setText("W");
W.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEvent evt) {
WActionPerformed(evt);
}
});

X.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
X.setText("X");
X.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEvent evt) {
XActionPerformed(evt);
}
});

Y.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
Y.setText("Y");
Y.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEvent evt) {
YActionPerformed(evt);
}
});

Z.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
Z.setText("Z");
Z.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEvent evt) {
ZActionPerformed(evt);
}
});

screen1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
screen1.setText("SCREEN_1");

guesses.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
guesses.setText("tries");

screen2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
screen2.setText("SCREEN_2");

startStopBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
startStopBtn.setText("START");
startStopBtn.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEvent evt) {
startStopBtnActionPerformed(evt);
}
});

invalidTFeild.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
invalidTFeild.setText("XXXXXXXXXXXXXXX");
invalidTFeild.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEvent evt) {
invalidTFeildActionPerformed(evt);
}
});

javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
this.setLayout(layout);
layout.setHorizontalGroup(
layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addGroup(layout.createSequentialGroup()
.addContainerGap()
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addGroup(layout.createSequentialGroup()
.addComponent(K)
.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
.addComponent(L)
.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
.addComponent(M)
.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
.addComponent(N)
.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
.addComponent(O)
.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
.addComponent(P)
.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
.addComponent(Q)
.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
.addComponent(R)
.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
.addComponent(S)
.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
.addComponent(T)
.addGap(0, 0, Short.MAX_VALUE))
.addGroup(layout.createSequentialGroup()
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addGroup(layout.createSequentialGroup()
.addGap(18, 18, 18)
.addComponent(guesses, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
.addComponent(A, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addGroup(layout.createSequentialGroup()
.addGap(75, 75, 75)
.addComponent(heading, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
.addGap(40, 40, 40)
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addComponent(screen2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
.addComponent(screen1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
.addGroup(layout.createSequentialGroup()
.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
.addComponent(invalidTFeild, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
.addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
.addComponent(B, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
.addComponent(C)
.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
.addComponent(D)
.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
.addComponent(E)
.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
.addComponent(F)
.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
.addComponent(G)))
.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
.addComponent(I)
.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
.addComponent(J)))
.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
.addGroup(layout.createSequentialGroup()
.addGap(28, 28, 28)
.addComponent(U)
.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
.addComponent(V)
.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
.addComponent(W)
.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
.addComponent(X)
.addGap(14, 14, 14)
.addComponent(Y)
.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
.addComponent(Z)
.addGap(18, 18, 18)
.addComponent(startStopBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
.addGap(0, 0, Short.MAX_VALUE))
);
layout.setVerticalGroup(
layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addGroup(layout.createSequentialGroup()
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addGroup(layout.createSequentialGroup()
.addContainerGap()
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
.addComponent(heading, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
.addComponent(guesses, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
.addGroup(layout.createSequentialGroup()
.addComponent(screen2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
.addComponent(screen1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
.addComponent(invalidTFeild, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
.addGap(18, 18, 18)
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
.addComponent(A)
.addComponent(B)
.addComponent(C, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
.addComponent(D, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
.addComponent(E, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
.addComponent(F, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
.addComponent(G, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
.addComponent(I, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
.addComponent(J, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
.addComponent(K, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
.addComponent(M)
.addComponent(N)
.addComponent(O)
.addComponent(P)
.addComponent(Q)
.addComponent(S)
.addComponent(T)
.addComponent(L, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
.addComponent(R, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
.addComponent(U)
.addComponent(V)
.addComponent(W)
.addComponent(X)
.addComponent(Y)
.addComponent(Z)
.addComponent(startStopBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
.addGap(35, 35, 35))
);
}//

private void headingActionPerformed(java.awt.event.ActionEvent evt) {
// TODO add your handling code here:
}   

private void AActionPerformed(java.awt.event.ActionEvent evt) {
//checkLetter("A");
}   

  
  
private void startStopBtnActionPerformed(java.awt.event.ActionEvent evt) {   
// TODO add your handling code here:
JButton btn = (JButton)evt.getSource();
if(btn.getText().equalsIgnoreCase("Start")) {
startGame();
btn.setText("Stop");
reset();
}
else if(btn.getText().equalsIgnoreCase("Stop")) {
stopGame();
btn.setText("Start");
}
count = 0;
revalidate();
repaint();
}

private void invalidTFeildActionPerformed(java.awt.event.ActionEvent evt) {
// TODO add your handling code here:
}   

private void BActionPerformed(java.awt.event.ActionEvent evt) {
// TODO add your handling code here:
}   

private void CActionPerformed(java.awt.event.ActionEvent evt) {
// TODO add your handling code here:
}   

private void DActionPerformed(java.awt.event.ActionEvent evt) {
// TODO add your handling code here:
}   

private void EActionPerformed(java.awt.event.ActionEvent evt) {
// TODO add your handling code here:
}   

private void FActionPerformed(java.awt.event.ActionEvent evt) {
// TODO add your handling code here:
}   

private void GActionPerformed(java.awt.event.ActionEvent evt) {
// TODO add your handling code here:
}   

private void IActionPerformed(java.awt.event.ActionEvent evt) {
// TODO add your handling code here:
}   

private void JActionPerformed(java.awt.event.ActionEvent evt) {
// TODO add your handling code here:
}   

private void KActionPerformed(java.awt.event.ActionEvent evt) {
// TODO add your handling code here:
}   

private void LActionPerformed(java.awt.event.ActionEvent evt) {
// TODO add your handling code here:
}   

private void MActionPerformed(java.awt.event.ActionEvent evt) {
// TODO add your handling code here:
}   

private void NActionPerformed(java.awt.event.ActionEvent evt) {
// TODO add your handling code here:
}   

private void OActionPerformed(java.awt.event.ActionEvent evt) {
// TODO add your handling code here:
}   

private void PActionPerformed(java.awt.event.ActionEvent evt) {
// TODO add your handling code here:
}   

private void QActionPerformed(java.awt.event.ActionEvent evt) {
// TODO add your handling code here:
}   

private void RActionPerformed(java.awt.event.ActionEvent evt) {
// TODO add your handling code here:
}   

private void SActionPerformed(java.awt.event.ActionEvent evt) {
// TODO add your handling code here:
}   

private void TActionPerformed(java.awt.event.ActionEvent evt) {
// TODO add your handling code here:
}   

private void UActionPerformed(java.awt.event.ActionEvent evt) {
// TODO add your handling code here:
}   

private void VActionPerformed(java.awt.event.ActionEvent evt) {
// TODO add your handling code here:
}   

private void WActionPerformed(java.awt.event.ActionEvent evt) {
// TODO add your handling code here:
}   

private void XActionPerformed(java.awt.event.ActionEvent evt) {
// TODO add your handling code here:
}   

private void YActionPerformed(java.awt.event.ActionEvent evt) {
// TODO add your handling code here:
}   

private void ZActionPerformed(java.awt.event.ActionEvent evt) {
// TODO add your handling code here:
}

// Every time the user clicks a button, the program checks whether that letter is part of the word. If it is then in place of the dashes the letter appears and if the letter isn't part of the word then nothing happens. The number of guesses increase every time the user guesses a letter.   

// Variables declaration - do not modify   
private javax.swing.JButton A;
private javax.swing.JButton B;
private javax.swing.JButton C;
private javax.swing.JButton E;
private javax.swing.JButton F;
private javax.swing.JButton G;
private javax.swing.JButton I;
private javax.swing.JButton J;
private javax.swing.JButton K;
private javax.swing.JButton L;
private javax.swing.JButton M;
private javax.swing.JButton N;
private javax.swing.JButton O;
private javax.swing.JButton P;
private javax.swing.JButton Q;
private javax.swing.JButton R;
private javax.swing.JButton S;
private javax.swing.JButton T;
private javax.swing.JButton U;
private javax.swing.JButton V;
private javax.swing.JButton W;
private javax.swing.JButton X;
private javax.swing.JButton Y;
private javax.swing.JButton Z;
private javax.swing.JLabel guesses;
private javax.swing.JTextField heading;
private javax.swing.JTextField invalidTFeild;
private javax.swing.JLabel screen1;
private javax.swing.JLabel screen2;
private javax.swing.JButton startStopBtn;
// End of variables declaration

public void startGame(){

screen1.setVisible(false);
screen2.setVisible(true);
guesses.setVisible(true);
invalidTFeild.setVisible(false);
}

//Everytime the user clicks this button, the program will select a random word from the string of words and display it in form of dashes.
public void stopGame(){
screen1.setVisible(true);
screen2.setVisible(false);
guesses.setVisible(false);
invalidTFeild.setVisible(true);
}
public void reset(){
count = 0;
if(currentWord == (words.length - 1))
currentWord = 0;
else
currentWord += 1;
guesses.setText(count + " tries");
  
}
public static void main(String[] args) {
// TODO code application logic here
JFrame frame = new JFrame();
HangmanG layout = new HangmanG();
frame.add(layout);
frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
frame.setSize(500, 300);
frame.setResizable(false);
frame.setLocationRelativeTo(null); //To center frame on the window
frame.setVisible(true);
}
}
